### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by BradHeff** [btiteam/xbtit-3.1#2]
Hi,

Just installed and imported the styles to database as directed on the website and now the site will not load any styles. Displaying just a white page.

Is there anyway to get it back as i forgot to backup the database. Can i get the insert command for last release 2.5 i think it is.

I tried adding the old style back into the fold and setting the default and my user style to it. No luck

mysql> select * from xbtit_style;
+----+--------------------+--------------------------+------------+
| id | style              | style_url                | style_type |
+----+--------------------+--------------------------+------------+
|  1 | Xbtit 2.0          | style/Xbtit_2.0          |          3 |
|  2 | Xbtit 3.0          | style/Xbtit_3.0          |          3 |
|  3 | Dark Lair 3.0      | style/darklair_3.0       |          3 |
|  4 | Frosted 3.0        | style/frosted_3.0        |          3 |
|  5 | Mint 3.0           | style/mintgreen_3.0      |          3 |
|  6 | Yellow Jacket 3.0  | style/thehive_3.0        |          3 |
|  7 | Dark Lair 2.0      | style/darklair_2.0       |          3 |
|  8 | Frosted 2.0        | style/frosted_2.0        |          3 |
|  9 | Mint 2.0           | style/mintgreen_2.0      |          3 |
| 10 | Yellow Jacket 2.0  | style/thehive_2.0        |          3 |
| 11 | Holiday Spirit 2.0 | style/holiday-spirit_2.0 |          3 |
+----+--------------------+--------------------------+------------+
11 rows in set (0.00 sec)

**Comment by l3oncoder** [comment]
Sorry for slow reply, Did you manage to sort this?
